# Generated by Django 4.1.4 on 2023-01-11 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='static/images/')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Handoff'), (3, 'Completed'), (4, 'Paused'), (5, 'Stopped'), (6, 'Put On Hold'), (7, 'Rejected')], default=0)),
                ('projected_revenue', models.BigIntegerField(default=0, null=True)),
                ('actual_net_revenue', models.BigIntegerField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('business_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.businessunit')),
                ('ideator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.program')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
