# Generated by Django 4.1.4 on 2023-01-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='actual_net_revenue',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='projected_revenue',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
