# Generated by Django 4.1.4 on 2023-01-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_alter_idea_actual_net_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(default='default.png', upload_to='static/images/'),
        ),
    ]
