# Generated by Django 4.1.4 on 2023-01-11 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(default='Not Specified', max_length=200, null=True)),
                ('state', models.CharField(default='Not Specified', max_length=200, null=True)),
                ('country', models.CharField(default='Not Specified', max_length=200, null=True)),
                ('is_jury', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('field_of_work', models.CharField(max_length=200, null=True)),
                ('years_of_experience', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('jury_business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.businessunit')),
                ('jury_programs', models.ManyToManyField(blank=True, to='program.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=10)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('business_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.businessunit')),
            ],
        ),
    ]
