# Generated by Django 4.1.4 on 2023-01-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_alter_businessunit_jury'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='busiess_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.businessunit'),
        ),
    ]
