# Generated by Django 4.1.4 on 2023-01-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_remove_businessunit_jury_businessunit_jury'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='jury_programs',
            new_name='programs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jury_business_unit',
        ),
        migrations.AddField(
            model_name='profile',
            name='business_units',
            field=models.ManyToManyField(blank=True, to='program.businessunit'),
        ),
    ]
