# Generated by Django 4.1.4 on 2023-01-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_invitation_busiess_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='busiess_unit',
            new_name='business_unit',
        ),
    ]
