# Generated by Django 4.1.4 on 2023-01-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(default='naem', max_length=200),
            preserve_default=False,
        ),
    ]
