# Generated by Django 4.1.4 on 2023-01-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_mobile'),
        ('account', '0012_invitation_name'),
    ]

    operations = [
    ]
