# Generated by Django 4.1.4 on 2023-01-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_merge_0011_alter_profile_mobile_0012_invitation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
