# Generated by Django 4.1.4 on 2023-01-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='business_unit',
        ),
    ]
