# Generated by Django 4.1.4 on 2023-01-11 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='jury',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='jury',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
